# Generated by Django 4.2.3 on 2024-10-19 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0002_alter_studentprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='current_week',
            field=models.IntegerField(default=1),
        ),
    ]
