# Generated by Django 4.2.3 on 2024-10-21 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0005_studentprofile_fee_balance_studentprofile_year'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnitRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateField(auto_now_add=True)),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.semester')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.student')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='attendance.unit')),
            ],
        ),
    ]
